##
# Provided by Sagar on 2023-05-16
##
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-kernel
  annotations:
    policies.kyverno.io/title: Check Node for CVE-2022-0185
    policies.kyverno.io/category: security-known-cve-protection
    policies.kyverno.io/scored: "true"
    policies.kyverno.io/severity: high
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Node
    policies.kyverno.io/description: >-
      Linux CVE-2022-0185 can allow a container escape in Kubernetes if left unpatched.
      The affected Linux kernel versions, at this time, are 5.10.84-1 and 5.15.5-2.
      For more information, refer to https://security-tracker.debian.org/tracker/CVE-2022-0185.
      This policy runs in background mode and flags an entry in the ClusterPolicyReport
      if any Node is reporting one of the affected kernel versions.      
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: kernel-validate
    match:
      any:
      - resources:
          kinds:
          - Node
    exclude:
      any:
      - resources:
          namespaces:
          - argocd
          - calico-system
          - cattle-fleet-system
          - cattle-impersonation-system
          - cattle-logging-system
          - cattle-monitoring-system
          - cattle-system
          - harbor
          - kube-system
          - linkerd
          - linkerd-cni
          - longhorn-system
          - tigera-operator
    validate:
      message: "Kernel is vulnerable to CVE-2022-0185."
      deny:
        conditions:
          any:
          - key: "{{request.object.status.nodeInfo.kernelVersion}}"
            operator: Equals
            value: "5.10.84-1"
          - key: "{{request.object.status.nodeInfo.kernelVersion}}"
            operator: Equals
            value: "5.15.5-2"
